swagger: '2.0'
info:
  title: shsh
  description: URL shortener
  version: 1.0.0
host: shsh-gateway-qwe52f3tqa-ey.a.run.app
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: https://shsh-core-be-qwe52f3tqa-ey.a.run.app/
  protocol: h2
security:
  - api_key: []
paths:
  /api:
    get:
      summary: Index API
      operationId: index
      responses:
        '200':
          description: A successful response
          schema:
            type: object
            
  /api/eren:
    post:
      summary: Eren API
      operationId: eren
      responses:
        '200':
          description: A successful response
          schema:
            type: object
      parameters:
        - in: body
          name: payload
          schema:
            type: object
            required:
              - token
                url
            properties:
              token:
                type: string
              url:
                type: string

  /api/mikasa:
    get:
      summary: Mikasa API
      operationId: mikasa
      responses:
        '200':
          description: A successful response
          schema:
            type: object
            
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"